// <auto-generated />
using System;
using DataPollingApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataPollingApi.Migrations
{
    [DbContext(typeof(S31JdfMachineHandlerContext))]
    partial class S31JdfMachineHandlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataPollingApi.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("XmlPath")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("xmlPath");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("job", (string)null);
                });

            modelBuilder.Entity("DataPollingApi.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("int(11)")
                        .HasColumnName("yearBuilt");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("machine", (string)null);
                });

            modelBuilder.Entity("DataPollingApi.Models.MachineJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JobId")
                        .HasColumnType("int(11)")
                        .HasColumnName("jobId");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int(11)")
                        .HasColumnName("machineId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "JobId" }, "jobId");

                    b.HasIndex(new[] { "MachineId" }, "machineId");

                    b.ToTable("machine_jobs", (string)null);
                });

            modelBuilder.Entity("DataPollingApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DataPollingApi.Models.UserJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JobId")
                        .HasColumnType("int(11)")
                        .HasColumnName("jobId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "JobId" }, "jobId")
                        .HasDatabaseName("jobId1");

                    b.HasIndex(new[] { "UserId" }, "userId");

                    b.ToTable("user_job", (string)null);
                });

            modelBuilder.Entity("DataPollingApi.Models.MachineJob", b =>
                {
                    b.HasOne("DataPollingApi.Models.Job", "Job")
                        .WithMany("MachineJobs")
                        .HasForeignKey("JobId")
                        .HasConstraintName("machine_jobs_ibfk_2");

                    b.HasOne("DataPollingApi.Models.Machine", "Machine")
                        .WithMany("MachineJobs")
                        .HasForeignKey("MachineId")
                        .HasConstraintName("machine_jobs_ibfk_1");

                    b.Navigation("Job");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("DataPollingApi.Models.UserJob", b =>
                {
                    b.HasOne("DataPollingApi.Models.Job", "Job")
                        .WithMany("UserJobs")
                        .HasForeignKey("JobId")
                        .HasConstraintName("user_job_ibfk_1");

                    b.HasOne("DataPollingApi.Models.User", "User")
                        .WithMany("UserJobs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_job_ibfk_2");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataPollingApi.Models.Job", b =>
                {
                    b.Navigation("MachineJobs");

                    b.Navigation("UserJobs");
                });

            modelBuilder.Entity("DataPollingApi.Models.Machine", b =>
                {
                    b.Navigation("MachineJobs");
                });

            modelBuilder.Entity("DataPollingApi.Models.User", b =>
                {
                    b.Navigation("UserJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
